// angular/src/app/single-show/single-show.component.ts
import { Component, OnInit } from '@angular/core';
import {ActivatedRoute} from '@angular/router';
import {ShowsService} from '../shows.service';
import {DomSanitizer} from '@angular/platform-browser'


@Component({
  selector: 'app-single-show',
  templateUrl: './single-show.component.html',
  styleUrls: ['./single-show.component.scss']
})
export class SingleShowComponent implements OnInit {

  show: any;
  constructor(private acticatedRoute: ActivatedRoute, private showsService: ShowsService,
              private sanitizer: DomSanitizer) { }

  ngOnInit() {
    this.acticatedRoute.params.subscribe((params: any) => {
      const id = params.id;
      this.showsService.getShowById(id).subscribe((show: any) => {
        document.title = show.name;
        this.show = show;
        this.show.summry = this.sanitizer.bypassSecurityTrustHtml(this.show.summary);
      })
    })
  }

}

<div *ngIf="show">
  <a [attr.href]="show.url"> <p>{{show.name}}</p></a>
   <p [innerHtml]="show.summary"></p>
  <a [attr.href]="show.url">
  <img  *ngIf="show.image" [src]="show.image.original"/>
  <img *ngIf="!show.image" src="/assets/images/no-img-portrait-text.png" />

  </a>

  <a [routerLink]="['/']">Go Back</a>
</div>

// react-app/src/components/single-show/single-show.js
import React from 'react';
import {Link} from 'react-router-dom';
import ShowsService from '../../shows-service';

async function getShow(showId, setShow) {
    const response = await ShowsService.lookupShow(showId);
    if (response.data) {

        setShow(response.data);
    }
}

function SingleShow({match}) {
    const id = match.params.id;

    const [show, setShow] =React.useState({show: {}})
    getShow(id, setShow);

    return (<div>
    <a href={show.url}> <p>{show.name}</p></a>
   <p>{show.summary}</p>
  <a href={show.url}>
  <img  src={ show.image? show.image.original: '/assets/images/no-img-portrait-text.png' }/>

  </a>

  <Link to="/">Go Back</Link>
</div>)
}

export default SingleShow;
