// angular/src/app/search-show/search-show.component.ts
import {Component, EventEmitter, OnInit, Output, Input} from '@angular/core';

@Component({
  selector: 'app-search-show',
  templateUrl: './search-show.component.html',
  styleUrls: ['./search-show.component.scss']
})
export class SearchShowComponent implements OnInit {
  @Input() searchTerm: string;

  @Output() search = new EventEmitter<string>()

  constructor() {
  }

  ngOnInit() {
  }

  submitForm() {
    this.search.emit(this.searchTerm);
  }
}

<form (submit)="submitForm()">
  <div>
    <input name="search-term" type="text" placeholder="Search term" [(ngModel)]="searchTerm">
    <i class="fas fa-search" (click)="submitForm()"></i>
  </div>
</form>

// react-app/src/components/search-show/search-show.js
import React from 'react';
import './search-show.scss';



class SearchShow extends React.Component {

    submitForm = (event) => {
        if (!this.props.onSearch) {
            throw Error('No onSearch callback is defined')
        }
        this.props.onSearch(this.searchTerm);
        event.preventDefault();
    }

    changeValue = (event) => {
        this.searchTerm =event.target.value;
    }

    render() {
        this.searchTerm = this.props.searchTerm;

        return (<form onSubmit={this.submitForm}>
            <div>
                <input name="search-term" type="text" placeholder="Search term" defaultValue={this.searchTerm} onChange={this.changeValue}/>
                <i className="fas fa-search" onClick={this.submitForm}></i>
            </div>
        </form>)
    }
}

export default SearchShow;
