// react-app/src/components/shows-list/shows-list.js
import React from 'react';
import './shows-list.scss';


function ShowsList(props) {
    const {shows} = props;
    if (shows) {
        console.log('prop.shows', props.shows)
        return (<div className="shows-container">
            {shows.map(show => {
                return (<div><p>{show.name}</p> <img alt={show.name}
                                                                src={show.image.medium}/></div>);
            })
            }
        </div>)
    }
    return (<p>Shows list works!!!</p>)
}

export default ShowsList;

// angular/src/app/shows-list/shows-list.component.ts
import {Component, Input, OnInit} from '@angular/core';

@Component({
  selector: 'app-shows-list',
  templateUrl: './shows-list.component.html',
  styleUrls: ['./shows-list.component.scss']
})
export class ShowsListComponent implements OnInit {

  @Input() shows: any[]
  constructor() { }

  ngOnInit() {
  }

}

<div class="shows-container" *ngIf="shows">

  <div *ngFor="let show of shows">
    <a [routerLink]="['show', show.id]"><p>{{show.name}}</p>
    <img *ngIf="show.image" [src]="show.image.medium" />
    </a>
  </div>
</div>
